apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
spec:
  params:
    - name: image-name
      type: string
    - name: image-tag
      type: string
  workspaces:
    - name: source
  steps:
    - name: build
      image: quay.io/buildah/stable:latest
      securityContext:
        privileged: true
      script: |
        #!/bin/bash
        cd $(workspaces.source.path)
        
        # Build the container image
        buildah build-using-dockerfile \
          --file ./Dockerfile \
          --tag $(params.image-name):$(params.image-tag) \
          .
        
        # Push to internal registry
        buildah push $(params.image-name):$(params.image-tag) \
          docker://image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/$(params.image-name):$(params.image-tag)
        
        echo "Image built and pushed successfully"