apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
spec:
  workspaces:
    - name: source
  steps:
    - name: install-deps
      image: registry.redhat.io/rhel8/python-311:1-92.1749045878
      script: |
        #!/bin/bash
        cd $(workspaces.source.path)
        pip install -r requirements.txt
        pip install -r requirements-test.txt
        
    - name: run-tests
      image: registry.redhat.io/rhel8/python-311:1-92.1749045878
      script: |
        #!/bin/bash
        cd $(workspaces.source.path)
        python -m pytest test_app.py -v --cov=app --cov-report=term-missing
        echo "Tests completed successfully"