apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: flask-app-trigger-template
spec:
  params:
    - name: git-revision
    - name: git-commit-message
    - name: git-repo-url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: flask-app-pipeline-run-
      spec:
        pipelineRef:
          name: flask-app-pipeline
        params:
          - name: git-url
            value: $(tt.params.git-repo-url)
          - name: git-revision
            value: $(tt.params.git-revision)
          - name: image-tag
            value: $(tt.params.git-revision)
        workspaces:
          - name: shared-workspace
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: flask-app-trigger-binding
spec:
  params:
    - name: git-revision
      value: $(body.head_commit.id)
    - name: git-commit-message
      value: $(body.head_commit.message)
    - name: git-repo-url
      value: $(body.repository.clone_url)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: flask-app-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - ref: flask-app-trigger-binding
      template:
        ref: flask-app-trigger-template