apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flask-app
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: https://github.com/diksha1999/flask_cicd_demo
    targetRevision: main
    path: openshift
  destination:
    server: https://kubernetes.default.svc
    namespace: flask-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
